people = {
    "Leonardo DiCaprio": ["Actor", "Environmentalist", "Philanthropist"],
    "Taylor Swift": ["Singer", "Songwriter", "Businesswoman"],
    "Elon Musk": ["Entrepreneur", "Innovator", "Space Enthusiast"],
    "Oprah Winfrey": ["Media Mogul", "Philanthropist", "Talk Show Host"],
    "Tom Hanks": ["Actor", "Producer", "Film Director"],
    "Serena Williams": ["Tennis Player", "Entrepreneur", "Philanthropist"],
    "Bill Gates": ["Entrepreneur", "Philanthropist", "Tech Visionary"],
    "Emma Watson": ["Actor", "Activist", "UN Women Goodwill Ambassador"],
    "Dwayne Johnson": ["Actor", "Wrestler", "Businessman"],
    "Michelle Obama": ["Former First Lady", "Author", "Advocate"],
    "Jeff Bezos": ["Entrepreneur", "Philanthropist", "Amazon CEO"],
    "Beyoncé": ["Singer", "Songwriter", "Entrepreneur"],
    "Keanu Reeves": ["Actor", "Philanthropist", "Internet Meme Icon"],
    "Warren Buffett": ["Investor", "Philanthropist", "Business Tycoon"],
    "Angelina Jolie": ["Actor", "Humanitarian", "Film Director"],
    "Mark Zuckerberg": ["Entrepreneur", "Philanthropist", "Social Media Pioneer"],
    "Usain Bolt": ["Sprinter", "Athlete", "World Record Holder"],
    "Ellen DeGeneres": ["Comedian", "TV Host", "Advocate"],
    "Malala Yousafzai": ["Activist", "Nobel Laureate", "Education Advocate"],
    "Ada Lovelace": ["Pioneer", "Analytical Engine", "Mathematics"],
    "Grace Hopper": ["Innovator", "COBOL Developer", "Admiral"],
    "Alan Turing": ["Trailblazer", "Enigma Codebreaker", "Theoretical Computer Science"],
    "Tim Berners-Lee": ["Revolutionary", "World Wide Web", "Information Technology"],
    "Donald Knuth": ["Algorithmist", "The Art of Computer Programming", "Mathematics"],
    "Margaret Hamilton": ["ApolloCoder", "Software Engineering", "Space Exploration"],
    "Linus Torvalds": ["Pioneer", "Linux Kernel", "Open Source"],
    "Larry Page": ["Googler", "Search Engine", "Entrepreneurship"],
    "Sergey Brin": ["Googler", "Internet Programmer", "Innovation"],
    "Guido van Rossum": ["Pythonista", "Python", "Programming Languages"],
    "Richard Stallman": ["Hacktivist", "Free Software Movement", "GNU"],
    "Mark Zuckerberg": ["Internet Analyst", "Social Media", "Entrepreneurship"],
    "Dogecoin": ["Meme Icon", "Shiba Inu", "Cryptocurrency Mascot"]
}
